#!/bin/bash
clear
echo -e "
 \t 
                      ~ Добро пожаловть в ShefOS центр управления ~
                                      
                 |---------------------------------------------------------|
                 | ( 1 )--> Установить драйвера Intel, Nvidia, Amd         |
                 |                                                         |
                 | ( 2 )--> Исправить ключи GPG в ShefOS                   |
                 |                                                         |
                 | ( 3 )--> Включить буст графики Intel введите            |
                 |                                                         |
                 | ( 4 )--> Установить репозиторий BlackaArch для пентеста |
                 |                                                         |   
                 | ( 5 )--> Устранить неполадки с ключами GPG введите      |
                 |                                                         | 
                 | ( 6 )--> Установить Dotnet Prefix в LuxWine             |
                 |                                                         |
                 | ( 7 )--> Установить Ядро 6.15 ( Linux 6.15 )            |
                 |                                                         |
                 | ( 8 )--> Fix Исправление Balena-Etcher                  |
                 |                                                         |
                 | ( 9 )--> Исправление HP-ToolBOX HPliP                   |
                 |---------------------------------------------------------|"
echo -n "
                      -> Введите значение : 1 ; 2 ; 3 .... : "
read main_menu
      case "$main_menu" in
         "1" ) clear ;
         cd ~/ ; git clone https://github.com/linuxshef/drivers.git ; cd drivers ; ./Drivers ;
         cd ~/ ; rm -Rf drivers ; rm -Rf shefos-control
           ;;
         "2" ) clear ;
         sudo pacman-mirrors --fasttrack ;
         sudo pacman -Sy gnupg archlinux-keyring manjaro-keyring chaotic-keyring --noconfirm ;
         sudo rm -r /etc/pacman.d/gnupg ;
         sudo pacman-key --init ;
         sudo pacman-key --populate archlinux manjaro chaotic ;
         sudo pacman-key --refresh-keys ;
         sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com ;
         sudo pacman-key --lsign-key 3056513887B78AEB ;
         sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' --noconfirm ;
         sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm ;
         sudo pacman -Sy gnupg archlinux-keyring manjaro-keyring chaotic-keyring chaotic-mirrorlist --noconfirm ;
         rm -Rf shefos-control
           ;;
         "3" ) clear ; sudo systemctl enable --now igpu ; echo '    Выполнено :)  ' ; rm -Rf shefos-control
           ;;
         "4" ) clear ;
         cd ~/ ; git clone https://github.com/linuxshef/hackzone.git ; cd hackzone ; ./blackarchrep ;
         cd ~/ ; rm -Rf hackzone ; rm -Rf shefos-control
          ;;
         "5" ) clear ;
         cd ~/ ; git clone https://github.com/linuxshef/gpgfix.git ; cd gpgfix ; ./gpgfix ;
         cd ~/ ; rm -Rf gpgfix ; rm -Rf shefos-control
          ;;
         "6" ) clear ; cd ~/LuxWine/wprefixes/ ; wget https://github.com/VHSgunzo/wine-prefix/releases/download/v0.0.8/defprefix_dotnet.xz.lwpfx ;
          unsquashfs -f -d defprefix_dotnet defprefix_dotnet.xz.lwpfx ; echo '    Выполнено :)  ' ;
          cd ~/ ; rm -Rf shefos-control
          ;;
          "7" ) clear ;
          sudo rm /var/lib/pacman/db.lck >/dev/null 2>&1; RETVAL=$? ;
          sudo pacman -Syy --noconfirm ;
          sudo pacman -Rsc linux614 linux614-headers linux614-acpi_call --noconfirm ;
          sudo pacman -Syy linux615 linux615-headers linux615-acpi_call --noconfirm ;
          sudo mkinitcpio -p linux615 ; sudo update-grub ; reboot
          ;;
          "8" ) clear ;
          cd ~/ ; wget https://files.legalloli.net/filebrowser/api/public/dl/jjS2ciPy/pkg/balena-etcher-bin-2.1.3-1-x86_64.pkg.tar.zst ;
          sudo pacman -R balena-etcher --noconfirm ;
          sudo pacman -U balena-etcher-bin-2.1.3-1-x86_64.pkg.tar.zst --noconfirm ;
          rm -Rf balena-etcher-bin-2.1.3-1-x86_64.pkg.tar.zst ;
          sudo sed -i s/'Icon=balena-etcher'/'Icon=etcher'/g /usr/share/applications/balenaEtcher.desktop
          ;;
          "9" ) clear ;
          sudo rm /etc/os-release ;
          sudo rm /usr/lib/os-release ;
          sudo cp os-release /usr/lib/ ;
          sudo ln -s /usr/lib/os-release /etc
      esac
