#!/bin/bash
clear
echo '



                                ~ Добро пожаловть в ShefOS центр управления ~

'
echo -e "
      \t                     -> Установить драйвера Intel, Nvidia, Amd введите    1   "

echo -e "
      \t                     -> Включить буст графики Intel введите    2   "

echo -e "
      \t                     -> Устарнить неполдки Chaotic-aur введите   3   "

echo -e "
      \t                     -> Установить репозиторий BlackaArch для пентеста введите  4  "
echo -e "
      \t                     -> Устранить неполадки с ключами GPG введите  5  "

echo -n "

                                     -> Введите значение : "
read main_menu
      case "$main_menu" in
         "1" ) clear ;
         cd ~/ ; git clone https://github.com/linuxshef/drivers.git ; cd drivers ; ./Drivers ;
         cd ~/ ; rm -Rf drivers ; rm -Rf shefos-control
           ;;
         "2" ) clear ; sudo systemctl enable --now igpu ; echo '    Выполнено :)  '
           ;;
         "3" ) clear ;
         cd ~/ ; git clone https://github.com/linuxshef/chaotic.git ; cd chaotic ; ./chaotic ;
         cd ~/ ; rm -Rf chaotic ; rm -Rf shefos-control
           ;;
         "4" ) clear ;
         cd ~/ ; git clone https://github.com/linuxshef/hackzone.git ; cd hackzone ; ./blackarchrep ;
         cd ~/ ; rm -Rf hackzone ; rm -Rf shefos-control
          ;;
         "5" ) clear ;
         cd ~/ ; git clone https://github.com/linuxshef/gpgfix.git ; cd gpgfix ; ./gpgfix ;
         cd ~/ ; rm -Rf gpgfix ; rm -Rf shefos-control
      esac
