#!/bin/bash
clear
echo -e "
 \t 
                      ~ Добро пожаловть в ShefOS центр управления ~
                                      
                 |---------------------------------------------------------|
                 | ( 1 )--> Установить драйвера Intel, Nvidia, Amd         | 
                 |                                                         |
                 | ( 2 )--> Включить буст графики Intel введите            |
                 |                                                         |
                 | ( 3 )--> Устарнить неполдки Chaotic-aur введите         |
                 |                                                         | 
                 | ( 4 )--> Установить репозиторий BlackaArch для пентеста |
                 |                                                         |   
                 | ( 5 )--> Устранить неполадки с ключами GPG введите      |
                 |                                                         | 
                 | ( 6 )--> Установить Dotnet Prefix в LuxWine             | 
                 |---------------------------------------------------------|"
echo -n "
                      -> Введите значение : 1 ; 2 ; 3 .... : "
read main_menu
      case "$main_menu" in
         "1" ) clear ;
         cd ~/ ; git clone https://github.com/linuxshef/drivers.git ; cd drivers ; ./Drivers ;
         cd ~/ ; rm -Rf drivers ; rm -Rf shefos-control
           ;;
         "2" ) clear ; sudo systemctl enable --now igpu ; echo '    Выполнено :)  '
           ;;
         "3" ) clear ;
         cd ~/ ; git clone https://github.com/linuxshef/chaotic.git ; cd chaotic ; ./chaotic ;
         cd ~/ ; rm -Rf chaotic ; rm -Rf shefos-control
           ;;
         "4" ) clear ;
         cd ~/ ; git clone https://github.com/linuxshef/hackzone.git ; cd hackzone ; ./blackarchrep ;
         cd ~/ ; rm -Rf hackzone ; rm -Rf shefos-control
          ;;
         "5" ) clear ;
         cd ~/ ; git clone https://github.com/linuxshef/gpgfix.git ; cd gpgfix ; ./gpgfix ;
         cd ~/ ; rm -Rf gpgfix ; rm -Rf shefos-control
          ;;
         "6" ) clear ; cd ~/LuxWine/wprefixes/ ; wget https://github.com/VHSgunzo/wine-prefix/releases/download/v0.0.8/defprefix_dotnet.xz.lwpfx ;
          unsquashfs -f -d defprefix_dotnet defprefix_dotnet.xz.lwpfx ; echo '    Выполнено :)  ' ;
          cd ~/ ; rm -Rf shefos-control
      esac
